version: '3.7'
services:
    redis:
        image: "redis:latest"
        networks:
            - deploy
        volumes:
            - ./redis-data:/var/lib/redis
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        environment: 
            - REDIS_PORT=6379

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_USER=super
            - POSTGRES_PASSWORD=hahaha321
            - POSTGRES_DB=mydb
        ports:
            - "5151:5432"
        networks: 
            - deploy
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    nodejs:
        image: backend:latest
        ports:
            - "2000:2000"
        depends_on:
            - postgres
            - redis            
        networks:
            - deploy
        depends_on:
            - postgres
        environment: 
            - DB_USER=super
            - DB_DATABASE=mydb
            - DB_PASS=hahaha321
            - DB_HOST=postgres
            - SERVICEPORT=2000
            - REDIS_PORT=6379

    

networks:
    deploy:
