version: "3.7"
services:
     postgres:
         image: postgres:latest
         ports:
             - "5555:5432"
         networks :
             - samplenet
         volumes:
             - ./pgdata:/var/lib/postgresql/data
         environment:
             POSTGRES_PASSWORD: hahaha321
             POSTGRES_USER: super
             POSTGRES_DB: mydb
     nodejs:
         image: backend:1.3.0
         ports:
             - "7171:2000"
         networks:
             - samplenet
         environment:
             - PGUSER=super
             - PGHOST=postgres
             - PGDATABASE=mydb
             - PGPASSWORD=haha321
             - PGPORT=5432
             - SERVICEPORT=2000
networks:
  samplenet:
