version: '3.7'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_USER=super
            - POSTGRES_PASSWORD=hahaha321
            - POSTGRES_DB=mydb
        ports:
            - "5151:5432"
        networks: 
            - deploy
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    backend:
        image: backend:latest
        ports:
            - "2000:2000"
        networks:
            - deploy
        depends_on:
            - postgres
        environment: 
            - DB_USER=super
            - DB_DATABASE=mydb
            - DB_PASS=hahaha321
            - DB_HOST=postgres
            - SERVICEPORT=2000

    redis:
        image: redis
        command: redis-server --requirepass kodekonan
        container_name: redis
        environment: 
            - REDIS_PORT=6379
        ports: 
            - 6379:6379
        networks:
            - deploy
        volumes:
            - ./redis-data:/var/lib/redis

networks:
    deploy:
