version: '3.3'

services:
    backend:
        image: 32480/backend:dev
        container_name: backend
        ports:
            - 3000:3000
        networks:
            - deploy
        depends_on:
            - postgres
        environment: 
            - PORT=2000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - DB_HOST=postgres
            - DB_USER=super
            - DB_PASSWORD=hahaha321
            - DB_NAME=mydb
            - JWT_KEYS=awokawokawok
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 200M
                reservations:
                    cpus: '1'
                    memory: 200M    
    postgres:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=super
            - POSTGRES_PASSWORD=hahaha321
            - POSTGRES_DB=mydb
        ports:
            - 5432:5432
        networks: 
            - deploy
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    redis:
        image: redis
        command: redis-server --requirepass kodekonan
        container_name: redis
        environment: 
            - REDIS_PORT=6379
        ports: 
            - 6379:6379
        networks:
            - deploy
        volumes:
            - ./redis-data:/var/lib/redis

networks:
    deploy:
        driver: bridge
    
volumes:
    postgres-data:
    redis-data:
