version: '3.3'
services:
    postgres:
        image: postgres:latest
        ports:
            - 5151:5432
        networks: 
            - deploy
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=nopal
            - POSTGRES_PASSWORD=hahaha321
            - POSTGRES_DB=mydb

    redis:
        image: redis
        command: redis-server --requirepass redispass123
        container_name: redis
        environment: 
            - REDIS_PORT=6379
            - REDIS_PASSWORD=redispass123
        
        networks:
            - deploy
        volumes:
            - ./redis-data:/var/lib/redis


    nodejs:
        image: afsanarozan/cafe-backend
        ports:
            - 9191:2000
        depends_on:
            - postgres
            - redis    
        networks:
            - deploy
        environment: 
            - DB_USER=nopal
            - DB_DATABASE=cafe-backend
            - DB_PASS=hahaha321
            - DB_HOST=postgres
            - REDIS_HOST=redis
            - REDIS_PASS=redispass123
            - REDIS_PORT=6379
            - JWT_KEYS=AUx857wf^p!fp>+Nx5KK-.xucu7p

networks:
    deploy:
   
    
volumes:
    postgres-data:
    redis-data:
