version: '3.3'
services:
    redis:
        image: redis
        command: redis-server --requirepass redispass123
        container_name: redis
        environment: 
            - REDIS_PORT=6379
            - REDIS_PASSWORD=redispass123
        
        networks:
            - deploy
        volumes:
            - ./redis-data:/var/lib/redis

    postgres:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=hahaha321
            - POSTGRES_DB=mydb
        ports:
            - 5433:5432
        networks: 
            - deploy
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    nodejs:
        image: backend:latest
        ports:
            - 2000:2000
        depends_on:
            - postgres    
        networks:
            - deploy
        depends_on:
            - postgres
        environment: 
            - DB_USER=postgres
            - DB_DATABASE=mydb
            - DB_PASS=hahaha321
            - DB_HOST=postgres
            - SERVICEPORT=2000
            - REDIS_HOST=redis
            - REDIS_PASSWORD=redispass123
            - REDIS_PORT=6379
            - JWT_KEYS=awokawokawok
        deploy:
            resources:
                limits:
                    cpus: '0.001'
                    memory: 50M
                reservations:
                    cpus: '0.0001'
                    memory: 20M    

networks:
    deploy:
